### ISSUE TITLE
BanManagerImpl - Not banning because it is contained in an IANA-reserved block such as 192.168.0.0/16

### ISSUE THREAD

**Issue by judfromhud** [Aldaviva/Fail2Ban4Win#30] opened 2023-06-30 21:05 UTC
Blocking private addresses was my goal for this but was getting this message when trying to ban something like 192.168.1.7/32. Is there any way to ignore this or force the ban?

Also, 192.168.1.7 was used in your example for OpenSSH so I'm not sure if this is by design or not.

**Comment by Aldaviva** [comment] 2023-06-30 21:45
It's by design right now (the OpenSSH example was a little contrived to show the event schema). But I can add a configuration option so you can disable it and block the reserved subnets.

**Comment by judfromhud** [comment] 2023-06-30 21:59
That would be great. Thank you!

**Comment by Aldaviva** [comment] 2023-06-30 23:36
You can try running this [development snapshot](https://github.com/Aldaviva/Fail2Ban4Win/actions/runs/5427792974)'s [build](https://github.com/Aldaviva/Fail2Ban4Win/suites/13991084468/artifacts/780493181) and see if that lets the LAN address get banned. If that works then I can release it as 1.2.0.

The new property to add to `configuration.json` is
```json
"neverBanReservedSubnets": false,
```

This will allow all subnets in `10.0.0.0/8`, `172.16.0.0/12`, and `192.168.0.0/16` to get banned. If there are specific addresses or ranges within those which you still don't want to get banned, you can always manually add them back to the `neverBanSubnets` array.

**Comment by judfromhud** [comment] 2023-07-01 01:46
Ran a few tests and it's adding firewall rules for the private subnets. This is much appreciated, thank you!

**Comment by Aldaviva** [comment] 2023-07-03 06:49
Glad it's working! Released as [1.2.0](https://github.com/Aldaviva/Fail2Ban4Win/releases/tag/1.2.0).

**Closed by Aldaviva** 2023-07-03 06:49 UTC
Labels: enhancement
